# Generated by Django 3.2 on 2022-03-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_user', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=100, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('impression', models.TextField(blank=True)),
                ('review', models.IntegerField()),
                ('create_user', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=100, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelfLibrary.categories')),
            ],
        ),
    ]
