# Generated by Django 3.2 on 2022-03-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelfLibrary', '0002_auto_20220306_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
